### ISSUE TITLE
iOS touch input

### ISSUE THREAD

**Issue by Westbrook** [pshihn/planar-range#5]
When attempting to move a handle in iOS if the user doesn't pause before attempting to move the handle the interaction will be read as a scroll rather than a drag action.

Even if you immediately swipe left/right, which does catch the handle the continuation of the motion seems to be converted to scroll when moved to up/down.

**Comment by pshihn** [comment]
should be resolved in v0.3.1 by https://github.com/pshihn/planar-range/commit/08644c8c2ae5113945e73c25cbe7b987da1b42e1

Try it out now.

**Comment by Westbrook** [comment]
Looks awesome. Thanks!
